<?php
/** @var \Actiview\Honeypot\Block\Honeypot $block */
?>

<script type="text/x-magento-init">
    {
        "*": {
            "Actiview_Honeypot/js/model/honeypot": {
                "forms": <?= json_encode($block->getForms()) ?>,
                "fieldName": "<?= $block->escapeHtml($block->getFieldName()) ?>",
                "fieldClass": "<?= $block->escapeHtml($block->getFieldClass()) ?>"
            }
        }
    }
</script>